#makefile
#Timo Hauer
#17.11.2018

.PHONY: all

all: null leak array free funny

null:
	gcc -g -o bin/null src/null.c

leak:
	gcc -g -o bin/leak src/leak.c

array:
	gcc -g -o bin/array src/array.c

free:
	gcc -g -o bin/free src/free.c

funny:
	gcc -g -o bin/funny src/funny.c

realloc:
	gcc -g -o bin/funny src/realloc.c
